apiVersion: v1
kind: Service
metadata:
  name: spring-backend-service
spec:
  type: NodePort
  selector:
    app: spring-backend # ← 이 부분이 있어야 합니다
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      nodePort: 30081
