apiVersion: v1
kind: Service
metadata:
  # Ingress에서 참조할 이름
  name: chat-irumae-backend
spec:
  # Ingress를 사용하므로 ClusterIP 타입으로 변경
  type: ClusterIP

  # Backend Deployment의 Pod 라벨과 일치시켜 연결
  selector:
    app: spring-backend

  ports:
    - protocol: TCP
      # 서비스가 내부적으로 사용할 포트 (3001로 통일)
      port: 3001
      # 실제 컨테이너가 리스닝하는 포트 (Backend Deployment의 containerPort와 일치)
      targetPort: 3001
