apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  OPENAI_API_KEY: "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"
