apiVersion: v1
kind: Service
metadata:
  name: spring-frontend-service
spec:
  type: NodePort
  selector:
    app: spring-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
